version: '3.8'

services:
  app:
    build: .
    container_name: diversitree_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - diversitree_network
    depends_on:
      - mongodb
    env_file:
      - .env

  webserver:
    image: nginx:latest
    container_name: nginx_server
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - diversitree_network
    depends_on:
      - app

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27018:27017"
    networks:
      - diversitree_network
    environment:
      MONGO_INITDB_ROOT_USERNAME: adversitreedev
      MONGO_INITDB_ROOT_PASSWORD: adversitree

    # for a while must setup the mongodb on docker manually. (make bash script)
    # 1. make volume
    # 2. set real root access

networks:
  diversitree_network:

volumes:
  mongodb_data:
